server:
  port: 8081
  servlet:
    context-path: /psi1

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/psi_1?serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true             
    username: root
    password: 12345678
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL8Dialect  #與 MySQL 同版本
        format_sql: true